# default values for helm. yaml formatted

schedule: '10 * * * *'

image:
  repository: vvang/pgdump
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

pghost: acid-cango
pgport: 5432
pguser: postgres
secret_pgpass: postgres.acid-cango.credentials.postgresql.acid.zalan.do
secret_key: password

storage:
  size: 1Gi

